backend:
  name: github
  repo: amki618/amki618   # your github repo

media_folder: "images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Products"
    files:
      - file: "data/products.json"
        label: "Products List"
        name: "products"
        fields:
          - label: "Products"
            name: "products"
            widget: "list"
            fields:
              - {label: "Category", name: "category", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}