backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Products"
    files:
      - file: "data/products.json"
        label: "Products List"
        name: "products"
        fields:
          - label: "Products"
            name: "products"
            widget: "list"
            fields:
              - label: Category
                name: category
                widget: select
                options:
                  - Sarees
                  - Dresses
                  - Lehengas
                  - Anarkalis
                  - Kurtis
                  - Cord Sets
              - label: Image
                name: image
                widget: image
